### ISSUE TITLE
Add AttachmentEditor

### ISSUE THREAD

**Issue by jNery** [Esri/arcgis-toolkit-dotnet#109]
- [x]  dev @jNery
- [ ]  qa 

Create an AttachmentEditor similar to previous API https://developers.arcgis.com/silverlight/sample-code/start.htm#ToolkitAttachmentEditor
that will allow users to work with ArcGISFeatureTable add/update/delete attachments and open attachment for preview and/or save attachment locally.
Should also handle auto-submission of attachment edits for ServiceFeatureTable.

**Comment by jNery** [comment]
@mbranscomb : Should this issue also be closed or re-considered for v100.0?

**Comment by shaharbukra** [comment]
@jNery @mbranscomb please consider implement it for all .Net supported API's :)

**Comment by mbranscomb** [comment]
@shaharbukra Thanks for the feedback, we'll be working on the Toolkit components over the coming weeks.
