### ISSUE TITLE
Legend Control Displays Wrong Symbols for Items

### ISSUE THREAD

**Issue by bromamano** [Esri/arcgis-toolkit-dotnet#125]
I am trying to incorporate the Legend control into my application.  I noticed however that the symbols for the layers are not showing up properly associated withe the layer names.  Please help

**Comment by dotMorten** [comment]
Hi @bromamano. Could you share a repro case, or some screenshots showing the problem and describing what you expected to happen?

**Comment by dotMorten** [comment]
New legend for v100.x is replacing this control
