### ISSUE TITLE
SymbolDisplay can't synchronize with layer's symbol v100.1

### ISSUE THREAD

**Issue by HTKing** [Esri/arcgis-toolkit-dotnet#133]
when i customer toc with SymbolDisplay,I binding layer symbol to SymbolDisplay's Symbol,when I modify
layer symbol,the map layer's symbol change immediately,but SymbolDisplay is old symbol

**Comment by dotMorten** [comment]
@HTKing Would you mind sharing how you are setting up the binding, or share a small sample that reproduces this problem?

**Comment by dotMorten** [comment]
@HTKing I think I was able to reproduce it and added a fix
