### ISSUE TITLE
TableOfContents UpdateScaleVisiblity crashes when map content was loaded from code

### ISSUE THREAD

**Issue by gkmiel** [Esri/arcgis-toolkit-dotnet#153]
Hi,
I have got exception "Invalid argument: Scale is less than or equal to zero" when my map view is bound to MapViewModel. I downloaded toolkit code from GitHub and found what in UpdateScaleVisiblity scale object HasValue is true, but Value is equal to NaN. So I added additional check to if statement:

`
if (scale.HasValue && (!double.IsNaN(scale.Value)) && layerContentList != null) {
.....
}
`

Now it works.
Best regards
Gintautas

**Comment by dotMorten** [comment]
Thank you. I believe this was already fixed as part of a re-write of the layer content models to support reuse for both Legend and ToC:
https://github.com/Esri/arcgis-toolkit-dotnet/blob/master/src/Esri.ArcGISRuntime.Toolkit/Esri.ArcGISRuntime.Toolkit/UI/Controls/LayerList/LayerContentViewModel.cs#L203-L206

If you're still seeing this, feel free to re-open.
