### ISSUE TITLE
Is there a package compatible with .net runtime (wpf)  100.2.1

### ISSUE THREAD

**Issue by mquetel** [Esri/arcgis-toolkit-dotnet#174]
In attempting to install the latest NuGet (at least that I can find) it appears the package has a constraint that makes it incompatible with anything from 100.20 and above.  How do I get a version built for your current release (100.2.1) of runtime for .net (wpf)?

This is the error I am getting:

`Unable to resolve dependencies. 'Esri.ArcGISRuntime.WPF 100.2.1' is not compatible with 'Esri.ArcGISRuntime.Toolkit.WPF 100.1.0-beta2 constraint: Esri.ArcGISRuntime.WPF (>= 100.1.0 && < 100.2.0)'.`

**Comment by dotMorten** [comment]
We're trying to wrap up a release for 100.2.1. Until then you can use the AppVeyor nuget server which has the latest versions that are in the master branch. It's all documented in readme.md, but it was sort of hidden away, so I just updated the page to put it into its own section.
