### ISSUE TITLE
WPF TimeSlider visual issues

### ISSUE THREAD

**Issue by dotMorten** [Esri/arcgis-toolkit-dotnet#193]
A few issues with rendering the time slider in WPF:

![image](https://user-images.githubusercontent.com/1378165/38640805-2a89ecd0-3d8a-11e8-9dac-7ed154c193db.png)

- [ ] 1. The play icon isn't transparent.
- [ ] 2. The thumb is clipped (reducing right-margin to 0 seems to resolve this)
- [ ] 3. Right-most part of slider is clipped
- [ ] 4. The slider can't go to the last right-most spot
- [ ] 5. If initializing props with the geoview, the slider won't move but is stuck on the last position (`await slider.InitializeTimePropertiesAsync(mapView);`)

Sample-code:

```
var layer = new FeatureLayer(new Uri("http://services1.arcgis.com/VAI453sU9tG9rSmh/arcgis/rest/services/WorldGeo_HumanCulture_LifeExpectancy_features/FeatureServer/0"));
Map.OperationalLayers.Add(layer);
await layer.LoadAsync();
await slider.InitializeTimePropertiesAsync(layer);
```

Reproduced on screen with scaling factor 1.5x

Wrt icons, there are symbol fonts that contains these and would function better on high-dpi screens rather than using raster images. 
⏵, ⏵⎸, ⎹⏴

**Comment by dotMorten** [comment]
@zwaap For now should the time-slider then just end at the last step it can snap to?

**Comment by zwaap** [comment]
@dotMorten that's one possibility.  The design as it stands has the slider ending wherever the specified full extent would have it.  There are multiple options, each of which has pros and cons - we should have a design issue/discussion to resolve it.

**Comment by zwaap** [comment]
@dotMorten it looks like the description has grown and this issue is becoming kind of a catch-all.  I'm thinking some items should be separated out into multiple issues?

On this:

> Wrt icons, there are symbol fonts that contains these and would function better on high-dpi screens rather than using raster images. 

Not sure what you mean - icons aren't being used.

**Comment by dotMorten** [comment]
@zwaap Thoughts on this issue?

**Comment by zwaap** [comment]
@dotMorten I don't know what in the description encompasses the original issue; it was edited many times.

**Comment by zwaap** [comment]
That said, the lack of transparency behind the play button and clipping of the thumb seem to be pretty straightforward visual issues of a common type.  Possibly the right edge of the slider being clipped as well, unless that has more to do with the conflict between what the time step intervals and the time extent specify.
