### ISSUE TITLE
TimeSlider: Don't assume that TimeSteps is a List

### ISSUE THREAD

**Issue by fragmer** [Esri/arcgis-toolkit-dotnet#196]
~The TimeSteps property is now settable, so~ we can't assume that it's implemented by a List.

https://github.com/Esri/arcgis-toolkit-dotnet/blob/2467b1e44ac706def70af250c1edfec6a8d83bf4/src/Esri.ArcGISRuntime.Toolkit/Esri.ArcGISRuntime.Toolkit/UI/Controls/TimeSlider/TimeSlider.cs#L1463-L1465

In fact, TimeSlider itself sets it to a non-List value here:

https://github.com/Esri/arcgis-toolkit-dotnet/blob/2467b1e44ac706def70af250c1edfec6a8d83bf4/src/Esri.ArcGISRuntime.Toolkit/Esri.ArcGISRuntime.Toolkit/UI/Controls/TimeSlider/TimeSlider.cs#L790

**Comment by fragmer** [comment]
Something like this should do the trick:
```cs
            var timeStepsList = (TimeSteps as IList<DateTimeOffset>) ?? TimeSteps.ToList();
```

**Comment by dotMorten** [comment]
I'll fix. I actually had that fix locally early on and things were working, but somehow got lost in committing. Thanks
