### ISSUE TITLE
Job Manager

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#200]
JobManager is a non-UI component that is useful for managing serialization of jobs between runs of an application.

For reference impl. see [ArcGIS Runtime SDK for iOS Toolkit](https://github.com/Esri/arcgis-runtime-toolkit-ios/blob/master/Sources/ArcGISToolkit/JobManager.swift)

- [ ] UWP 
- [ ] WPF 
- [ ] Xamarin.Android 
- [ ] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by ramtechjoe** [comment]
Has there been consideration of implementing the ios JobManager in the Xamarin.Forms API?

**Comment by mbranscomb** [comment]
@ramtechjoe This feature has been under consideration for a while. We'll discuss internally and try to factor into our release planning for v.next.

We greatly appreciate your feedback regarding the controls/components that are most valuable to you.
