### ISSUE TITLE
TimeSlider

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#201]
The TimeSlider is a utility Control that emits TimeExtent values typically for use with a view control to enhance the viewing of geographic features that have attributes based upon Date/Time information.

- [x] UWP 
- [x] WPF 
- [x] Xamarin.Android 
- [x] Xamarin.iOS
- [x] Xamarin.Forms

**Comment by zwaap** [comment]
Complete and verified
