### ISSUE TITLE
TemplatePicker

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#203]
The TemplatePicker control enables selecting a FeatureTemplate to use when creating a feature in an ArcGISFeatureTable. A FeatureTemplate defines both a default DrawingTool that could be used to draw the new feature and a default set of attributes (known as a prototype) for a new feature.

- [ ] UWP 
- [ ] WPF 
- [ ] Xamarin.Android 
- [ ] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by brysageek** [comment]
Would like to see this Feature as well, updating WPF app to latest runtime that used 10.27 Template picker, would also like to be able to use this in UWP and Xamarin Forms.  Have forked and will look at contributing.

**Comment by mbranscomb** [comment]
@brysageek We appreciate the feedback, thanks.

We certainly welcome bug fixes, but contributions towards features should start with some discussion to ensure the implementation is consistent with our roadmap for the Toolkit and/or to avoid the chance we're already working on the same feature.

**Comment by brysageek** [comment]
@mbranscomb, thanks for letting me know, I will hold off then, let me know how I can help 
thanks.
