### ISSUE TITLE
OverviewMap

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#206]
OverviewMap shows a smaller scale overview of the visible area for the associated MapView.

- [ ] UWP 
- [ ] WPF 
- [ ] Xamarin.Android 
- [ ] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by ldanzinger** [comment]
@mbranscomb there are additional requests to have it work bidirectionally, so that you can drag the extent in the overview map and have that update the main map - https://community.esri.com/thread/221870-move-overview-map

**Comment by nCastle1** [comment]
Duplicate of #360
