### ISSUE TITLE
TimeSlider:InitializeTimePropertiesAsync(MapView) does not initialize the timeslider.

### ISSUE THREAD

**Issue by pMaske** [Esri/arcgis-toolkit-dotnet#207]
Initializing the timeslider using InitializeTimePropertiesAsync(GeoView) does not initialize the slider. TimeSlider's CurrentExtent is remains null. It appears to be partially working , in the sense the ticks and fulltime extent on slider got drawn , by explicitly calling LoadAsync on layers in Geoview but current extent was still remained null.

```
 //Intialize via MapView
MyTimeSlider.InitializeTimePropertiesAsync(MyMapView); //Not working
```

Platform : Xamarin iOS
Nuget package used: https://ci.appveyor.com/project/DotNetRuntimeTeam/arcgis-toolkit-dotnet/build/artifacts

Test app:
[TimeSliderTest.zip](https://github.com/Esri/arcgis-toolkit-dotnet/files/1925810/TimeSliderTest.zip)

**Comment by nCastle1** [comment]
Should be addressed by https://github.com/Esri/arcgis-toolkit-dotnet/pull/405
