### ISSUE TITLE
Legend: When MapView or SceneView has no Map or Scene initially, updating Map or Scene does not generate legend

### ISSUE THREAD

**Issue by adityatogani94** [Esri/arcgis-toolkit-dotnet#209]
Two `workflows` are possible when working with Legend

* Creating a `new map/scene` and adding different layers to it and at the very end assigning this map to the `MapView/SceneView` - Does not work as the `GeoView` attached to the legend requires a `map/scene`.

* Assigning a `new map/scene` to the `MapView/SceneView`  and adding layers to the map/scene - Works

**Comment by dotMorten** [comment]
Fixed in #291
