### ISSUE TITLE
LayerLegend: WmtsLayer only shows layer name no symbols

### ISSUE THREAD

**Issue by adityatogani94** [Esri/arcgis-toolkit-dotnet#213]
`WmtsLayer` when added to the `GeoView` does not show the Legend but just the layer name.
`AGOL` displays the Legend. Also, the rest end point -> http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/WMTS/legend
returns a legend back.

![image](https://user-images.githubusercontent.com/14307332/39023739-5abd6c48-43f1-11e8-9d6b-d3d678802bcf.png)

**Comment by dotMorten** [comment]
This appears to be a limitation of the ArcGIS Runtime as well as the WMTS spec. Some WMTS services does have a `GetLegendGraphic` operation that's a non-standard request type (the service you linked to doesn't implement that either).
Closing this as a known limitation.
