### ISSUE TITLE
LayerLegend: RasterLayer does not display Legend

### ISSUE THREAD

**Issue by adityatogani94** [Esri/arcgis-toolkit-dotnet#214]
When adding a `RasterLayer` to the `GeoView`, runtime does not display anything.
Layer: http://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer
ArcGIS Pro returns a legend back.

![image](https://user-images.githubusercontent.com/14307332/39023905-37085726-43f2-11e8-8d48-7b1414e59c8f.png)

Note: Usually when you add `/Legend` at the end of a rest endpoint you get a legend back for ex. http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/WMTS/legend
But with this layer there is an extra step that adds parameters to the URL. So to get the legend for this raster layer the correct URL is http://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer/legend?bandIds=&renderingRule=&f=html

**Comment by dotMorten** [comment]
This is a limitation in the core Runtime API, and not the Toolkit. You can open a support issue with Esri Support. Once the runtime supports this, the toolkit would automatically inherit it.
