### ISSUE TITLE
Legend: ReverseLayerOrder does not reverse order but updates FilterByVisibleScale instead (XamarinForms only)

### ISSUE THREAD

**Issue by adityatogani94** [Esri/arcgis-toolkit-dotnet#215]
In Xamarin Forms, toggling the boolean `ReverseLayerOrder` affects `FilterByVisibleScale`. This happens as the wrong property changed handler is used [here](https://github.com/Esri/arcgis-toolkit-dotnet/blob/master/src/Esri.ArcGISRuntime.Toolkit/XamarinForms/Legend/Legend.cs#L112)

```C#
public static readonly BindableProperty ReverseLayerOrderProperty =
            BindableProperty.Create(nameof(ReverseLayerOrder), typeof(bool), typeof(Legend), false, BindingMode.OneWay, null, OnFilterByVisibleScaleRangePropertyChanged);
```
Instead of `OnFilterByVisibleScaleRangePropertyChanged` use `OnReverseLayerOrderPropertyChanged`

**Comment by dotMorten** [comment]
Verified fixed
