### ISSUE TITLE
Dependency problem when using Esri.ArcGISRuntime.WPF 100.3

### ISSUE THREAD

**Issue by b21** [Esri/arcgis-toolkit-dotnet#221]
After upgrading the Esri.ArcGISRuntime.WPF to the current version 100.3 it is not possible to use the Esri.ArcGISRuntime.Toolkit 100.2-beta3 anymore. The problem is, that the dependent Esri.ArcGISRuntime Version has to be 100.2.1, but the nuget.org package dependencies says it could be equals or greater than.

Best regards and thank you.

**Comment by dotMorten** [comment]
We're working on getting an update out soon...

**Comment by b21** [comment]
That would be beautiful. Thanks Morten.
