### ISSUE TITLE
Application breaks , if i right click to an empty layer which does not have features (Exception: TargetExtent is empty)

### ISSUE THREAD

**Issue by vwadhwa52** [Esri/arcgis-toolkit-dotnet#227]
I tried to add an empty layer (i.e without adding any features), but as soon as I right click it , the application goes into crash. This should be handeled.

**Comment by dotMorten** [comment]
Could you please add some more details, repro steps and a stack trace?

**Comment by vwadhwa52** [comment]
Hi I created a blank feature collection layer , but did not add any feature initially in Feature Collection Layer, and added it to Operational Layers of map view, and I am able to see the name of the layer in TOC provided by the toolkit , but If I right click on that checkbox of layer , my application crashes and I get exception as 
**System.ArgumentException was unhandled
Message: An unhandled exception of type 'System.ArgumentException' occurred in Esri.ArcGISRuntime.dll
Additional information: Invalid argument: Target extent is empty.**


the application should not crash , only the context menu for (zoom to layer) should be disabled

**Comment by dotMorten** [comment]
I've submitted a fix for now (pending review).
However note that we plan on pulling the ToC into it's own branch prior to the main release, so the TOC won't be part of the non-beta release at first, since it needs quite a lot of more work. Part of that work is to actually make the context menu a customizable thing, rather than hardcoded to specific options, so the above fix wouldn't really matter by then, as that would be a zoom-to-command that you would own.

**Comment by vwadhwa52** [comment]
Yeah that would be great , as we could add option to view the attribute
table in context menu and many other options . When can we expect for the
release ?

**Comment by dotMorten** [comment]
> When can we expect for the release ?

When we feel the quality is good enough. Until then you can always use the nuget packages that always contains latest in the Master branch on the AppVeyor build server (see the readme)

**Comment by vwadhwa52** [comment]
Yes , I am already using the latest one from nuget , but that itself has
given me the bug. How will I know , that the bug has been resolved ?

**Comment by dotMorten** [comment]
Fixed.

**Comment by vwadhwa52** [comment]
Hi Morten,
Where can I find the updated .dll of toolkit ?
I mean ,the dll in which this issue is fixed ?
