### ISSUE TITLE
Update Microsoft.NETCore.UniversalWindowsPlatform reference to v6.0.6

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#238]
Update Microsoft.NETCore.UniversalWindowsPlatform reference to v6.0.6:

- [ ] src/Esri.ArcGISRuntime.Toolkit/Common/Esri.ArcGISRuntime.Toolkit.csproj
- [ ] src/Esri.ArcGISRuntime.Toolkit.Xamarin.Forms/Esri.ArcGISRuntime.Toolkit.Xamarin.Forms.csproj
- [ ] src/Esri.ArcGISRuntime.Toolkit.Preview/Common/Esri.ArcGISRuntime.Toolkit.Preview.csproj

**Comment by dotMorten** [comment]
Implicitly updated to 6.1.9 by the move to use `<Project Sdk="MSBuild.Sdk.Extras/1.6.68">` in the projects
