### ISSUE TITLE
Compass control not appearing on iOS (Xamarin.Forms)

### ISSUE THREAD

**Issue by cmpalmer66** [Esri/arcgis-toolkit-dotnet#252]
With the layout below, the compass control appears in the correct position (upper right hand corner) on UWP and Android, but does not appear at all on iOS.

```
<Grid Grid.Row="1">
	<Grid.ColumnDefinitions>
		<ColumnDefinition x:Name="LegendColumn" Width="0" />
		<ColumnDefinition Width="*"/>
	</Grid.ColumnDefinitions>

	<forms:MapView x:Name="MV" ViewpointChanged="MapViewpointChanged" Grid.Column="1"
			   VerticalOptions="FillAndExpand" Map="{Binding Map}" />

	<esriTK:Compass x:Name="Compass" HorizontalOptions="End" Heading="0" VerticalOptions="Start" Margin="20" Grid.Column="1"
					GeoView="{x:Reference MV}" AutoHide="False" />
	<esriTK:ScaleLine Foreground="White" HorizontalOptions="Start" VerticalOptions="End" Grid.Column="1"
					Margin="20" MapView="{x:Reference MV}" />

	<ScrollView Grid.Column="0">
		<esriTK:Legend HorizontalOptions="Start" VerticalOptions="Start" 
					FilterByVisibleScaleRange="True" 
					IsVisible="True" GeoView="{x:Reference MV}" />
	</ScrollView>
</Grid>
```

**Comment by dotMorten** [comment]
Got a fix incoming, but you can workaround that by forcing the width/height on the control, and it'll render (unfortunately that'll expose a second bug that I do have a fix for too).
Thanks for reporting this.

**Comment by cmpalmer66** [comment]
Thanks for taking a look - I’ll give it a try.

**Comment by cmpalmer66** [comment]
Yes, it appears now, but I see the issue you're talking about. The compass is rotating on the wrong axis (or axes) when the map is rotated. Should this be entered as a new issue or is it in progress already?

**Comment by dotMorten** [comment]
It's already fixed if you pull latest source

**Comment by jessharrell** [comment]
I see this is marked with a 100.5 milestone. When can we expect the 100.5 nuget release or pre-release with this fix?

**Comment by dotMorten** [comment]
@jessharrell If you pull and build the latest source code, you should see this fixed in the generated package.

**Comment by jessharrell** [comment]
The latest nuget package in the Nuget Gallery is 100.4.0 and contains the bug. I'd like to update to an officially published package in my app in which the bug has been fixed. Is there a target date for the release of a new arcgis-toolkite-dotnet nuget package to Nuget Gallery?
