### ISSUE TITLE
Nuget package suggests 100.5 compatibility

### ISSUE THREAD

**Issue by Favorablestream** [Esri/arcgis-toolkit-dotnet#259]
I assume compatibility with version 100.5 of ArcGIS Runtime is coming in a future version of the toolkit based on the commit: 4c075f9255a0dace22294b374d34e94be5cb133b. Currently the Nuget package dependencies suggest that any runtime 100.4 or newer will be compatible:
![image](https://user-images.githubusercontent.com/16925791/59303112-8440c900-8c63-11e9-9bf3-fb5d6bb8ff17.png)
https://www.nuget.org/packages/Esri.ArcGISRuntime.Toolkit/
When starting the application however the toolkit is expecting a runtime 100.4 assembly to be loaded:
`System.IO.FileLoadException: Could not load file or assembly 'Esri.ArcGISRuntime, Version=100.4.0.0, Culture=neutral, PublicKeyToken=8fc3cc631e44ad86' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Esri.ArcGISRuntime, Version=100.4.0.0, Culture=neutral, PublicKeyToken=8fc3cc631e44ad86'
   at Esri.ArcGISRuntime.Toolkit.UI.Controls.ScaleLine..cctor()`
The 100.4 assembly is being redirected to 100.5 in our application however 100.5 is not expected 
 by the toolkit and will not load.

We're able to make the toolkit work with 100.5 by building it from source so no worries there. Just wondering if the Nuget dependencies should be updated? Or if there should be some internal assembly redirection going on?

Thanks

**Comment by dotMorten** [comment]
If you use WPF, make sure you turn on assembly redirect in project settings, and it should work.

We hope to have a v.100.5 out soon but working through some remaining issues (mainly with Legend on Xamarin)
