### ISSUE TITLE
How to remove selection behavior from the map legend layers

### ISSUE THREAD

**Issue by RP2606** [Esri/arcgis-toolkit-dotnet#265]
Hello dotMorten,

I have been googling a lot about this issue and ended up creating a ticket here for any sort of help that I can get. I wish to remove the selection behavior altogether (via mouse and tap) from the map legend layers. I don't want any kind of selections possible in there. If that is not possible, I would atleast want to know how to set the selection color to white/transparent??

Regards,
Reema

**Comment by RP2606** [comment]
This is an urgent issue. Can someone please help?

**Comment by mbranscomb** [comment]
@RP2606 Please post your question in the ArcGIS Runtime SDK for .NET community space:

https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net

Thanks

**Comment by dotMorten** [comment]
@RP2606 Which platform are you targeting?

**Comment by RP2606** [comment]
I have posted my question here now : 
https://community.esri.com/message/870680-how-to-remove-selection-behavior-from-the-map-legend-layers

we are working on UWP.

**Comment by dotMorten** [comment]
@RP2606 FYI it's ok to post toolkit-related questions here. Sorry for the misleading question earlier.

**Comment by RP2606** [comment]
Any updates please?

**Comment by dotMorten** [comment]
@rp2606 the team is deep into finishing update 6. If you need immediate assistance you can contact Esri support. I can give you some hints though: look at the control templates used. It's probably a setting on the listview control that you can set by overriding the control template.

**Comment by dotMorten** [comment]
Actually I believe this issue has already been addressed in the Legend PR currently being worked on:
![image](https://user-images.githubusercontent.com/1378165/63034300-ec7f7700-be6d-11e9-8f20-1bad0a0f89b9.png)

**Comment by dotMorten** [comment]
@RP2606 I believe this issue has been resolved with the latest commit in master.

**Comment by RP2606** [comment]
Not sure about that, but yes, I got it working. Setting the IsHitTestVisible property on Legend to False worked for me.
Thanks for your help.
