### ISSUE TITLE
log an entry when parcel layer isn't indexed

### ISSUE THREAD

**Issue by RP2606** [Esri/arcgis-toolkit-dotnet#269]
Hello dotMorten,

I am trying to figure out a way to know if the parcel layer is indexed or not. Using the ESRI ArcGIS Runtime for .NET, is it possible to determine in code what attribute indexes exist for a FeatureTable?  We are working on UWP.

Regards,
Reema

**Comment by mbranscomb** [comment]
@RP2606 I recommend posting this type of question in the [community forum](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).

**Comment by RP2606** [comment]
done. 
https://community.esri.com/message/873136-log-an-entry-when-parcel-layer-isnt-indexed
