### ISSUE TITLE
Improve support for iOS 13 dark mode

### ISSUE THREAD

**Issue by nCastle1** [Esri/arcgis-toolkit-dotnet#283]
Currently there are challenges with both the test apps and the individual toolkit components on iOS 13 in dark mode.

A few issues I noticed:
* [x] Legends are unreadable in dark mode - black text on black background
* [x] Popup viewer tables are hard to read - black text on dark grey background
* [x] scale line behavior is inconsistent - text color changes when going to dark mode, but the line color doesn't.

**Comment by dotMorten** [comment]
All controls tested in darkmode and fixed in PR 291

**Comment by dotMorten** [comment]
Fixed in #291
