### ISSUE TITLE
Master branch NuGet URL returns a 404

### ISSUE THREAD

**Issue by mquetel** [Esri/arcgis-toolkit-dotnet#284]
The readme.md for this project indicates that the master nuget branch can be found here: https://github.com/Esri/arcgis-toolkit-dotnet#master-branch-nuget-server

This URL returns a 404, so it's not clear to me where I can get the latest build.

**Comment by mquetel** [comment]
Looks like you all have moved both the lastest and stable to nuget.  The readme.md in [this ](https://github.com/Esri/arcgis-toolkit-dotnet#master-branch-nuget-server )section needs to be updated or removed.

**Comment by dotMorten** [comment]
We've moving away from appveyor and are in the process of setting up a new nuget server for master branch builds. Until then you'd need to build master yourself.
