### ISSUE TITLE
Esri.ArcGISRuntime.Toolkit.Xamarin.Forms 100.4.0 Layer Legend Content does not display without HeightRequest

### ISSUE THREAD

**Issue by roman536** [Esri/arcgis-toolkit-dotnet#285]
The Legend Content for Xamarin displays layer symbology properly on UWP or Android 7.0, but not on Android 9.0 (smartphone Samsung A50 or tablet Samsung).
After some hours I couldn’t bring Toolkit.Samples.Forms.Android to work to evaluate this behavior directly in your code (Toolkit.Samples.Forms.UWP works fine), so please take a look on the part of my code below including workaround with extra HeightRequest set.

I'm using latest stable Esri.ArcGISRuntime.Xamarin.Forms 100.6.0 with Esri.ArcGISRuntime.Toolkit.Xamarin.Forms 100.4.0.
.NET Framework 4.6.1 targeting pack
Windows 10 SDK (10.0.17134.0)
Android 9.0 - Android SDK Platform 28

ContentView:
xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:d="http://xamarin.com/schemas/2014/forms/design"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:esriTK="clr-namespace:Esri.ArcGISRuntime.Toolkit.Xamarin.Forms;assembly=Esri.ArcGISRuntime.Toolkit.Xamarin.Forms"
x:Class="TOC_Layer"

    <ContentView.Content>
        <Grid x:Name="Grid_Layers" IsVisible="True"
              VerticalOptions="Start" HorizontalOptions="Start" RowSpacing="0">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="240"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>
            ...
            <esriTK:LayerLegend x:Name="esriTK_LayerLegend" Grid.Column="0" Grid.Row="0" IsVisible="True"
                                IncludeSublayers="True" IsEnabled="True"
                                Margin="12,0,6,0"/>
        </Grid>
    </ContentView.Content>

public partial class TOC_Layer : ContentView
...
	ILayerContent LayerContent = ... // MyMapLayer
	esriTK_LayerLegend.LayerContent = LayerContent;

	// Android 9.0 needs extra space for Layer Content?
	if (...) // Android
	{
		IReadOnlyList<LegendInfo> LegendInfosLayer = await LayerContent.GetLegendInfosAsync();
		esriTK_LayerLegend.HeightRequest = LegendInfosLayer.Count * 32;
	}

**Comment by dotMorten** [comment]
Thank you for the detailed repro. I believe this is a duplicate of #233 
I'm going to close this, but feel free to re-open if you disagree.
(I should have a fix for this go in very soon)

**Comment by dotMorten** [comment]
Sorry. Reopening. 233 is for LayerLegend, not this one.

**Comment by roman536** [comment]
After update packages esriTK to 100.7 I became warning:
esriTK:LayerLegend is obsolete since update to 100.7.0 "Deprecated in favor or Legend control".
However, looking for little more I have switched to acquiring items from ILayerContent - GetLegendInfosAsync - LegendInfo - Symbol - SymbolDisplay.
It works great for me, so we can close this issue.
Thank you.
