### ISSUE TITLE
Table of Contents: how to add separator in context menu?

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-toolkit-dotnet#310]
Thank you again for the updated code of TOC. It is working smoothly in my application. The only thing I am struggling is, how to add a separator between items into the context menu? 

I check the following:
    public class TableOfContentsContextMenuEventArgs : RoutedEventArgs
    {
        public object TableOfContentItem { get; }
        public LegendInfo LegendInfo { get; }
        public ContextMenu Menu { get; }
        public IList<MenuItem> MenuItems { get; }
    }

MenuItems cannot add separator because separator is not derived from MenuItem class. I also tried Menu.ItemSource, but it is not working as well. 

Please advise if I miss something here. Thanks!

**Comment by dotMorten** [comment]
Good catch! We'd have to change the type (which we can do since this control still is in the preview package)

**Comment by dotMorten** [comment]
Actually you could override it by accessing the menu directly:
args.Menu.ItemsSource = null;
args.Menu.Items.Add(new Seperator());

**Comment by GeoITwinkle** [comment]
> Actually you could override it by accessing the menu directly:
> args.Menu.ItemsSource = null;
> args.Menu.Items.Add(new Seperator());

I tried it and it can add separator, but something is odd here:
1. I need to write args.Menus.IsOpen = true to force it open after adding all items, maybe this is by design?
2. All the icons I set for the menu items are not showing, not sure why.

I will do some testings tomorrow to figure it out.

Thanks!

**Comment by dotMorten** [comment]
It's just using context menu. If you can make it work with a normal wpf context menu, this one should work too

**Comment by GeoITwinkle** [comment]
> It's just using context menu. If you can make it work with a normal wpf context menu, this one should work too

I saw that there was a new commit, so I built the code and it allowed me to add separators, making the context menu look better. Thanks!

**Comment by dotMorten** [comment]
I didn't have a problem adding icons to the menu item. You can use [an Image with an ImageSource](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.menuitem.icon?view=netframework-4.8), or I just used a `TextBlock` with a symbol font:
```cs
 var zoomTo = new MenuItem() { Header = "Zoom To" };
zoomTo.Icon = new TextBlock() { Text = "", FontFamily = new FontFamily("Segoe UI Symbol") };
zoomTo.Click += (s, e) => mapView.SetViewpointGeometryAsync(layer.FullExtent);
args.MenuItems.Add(zoomTo);
```

**Comment by GeoITwinkle** [comment]
> I didn't have a problem adding icons to the menu item. You can use [an Image with an ImageSource](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.menuitem.icon?view=netframework-4.8), or I just used a `TextBlock` with a symbol font:
> 
> ```cs
>  var zoomTo = new MenuItem() { Header = "Zoom To" };
> zoomTo.Icon = new TextBlock() { Text = "", FontFamily = new FontFamily("Segoe UI Symbol") };
> zoomTo.Click += (s, e) => mapView.SetViewpointGeometryAsync(layer.FullExtent);
> args.MenuItems.Add(zoomTo);
> ```
> 
> ![image](https://user-images.githubusercontent.com/1378165/74757730-413fe800-522b-11ea-82f2-ae4984f13379.png)

The issue was that the icon (png file) did not show up when I overrode the context menu by the following. Besides, the height of the separator was too much, not like a separator at all.
args.Menu.ItemsSource = null;
args.Menu.Items.Add();

So, I pulled the latest code this morning, did not override the context menu, but did the traditional way as I did before via args.MenuItems.Add(), which shows the icon and separator correctly. Anyway, no worries, the latest code works now and everything looks good.

Thanks again!

**Comment by dotMorten** [comment]
And thank you. The main reason the ToC is in the preview-package is we just haven't had the time to really exercise it in a bunch of scenarios. That feedback you've provided has been great so far and identified several shortcomings and bugs, so please keep it coming!

**Comment by GeoITwinkle** [comment]
Glad that I can help improve the toolkit. Will keep you posted if run into issues or have new ideas.
