### ISSUE TITLE
Table of Contents: select and retrieve a symbol?

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-toolkit-dotnet#315]
As shown below, my mouse is right-clicking on the symbol called "Sewer Issues". However, TableOfContentContextMenuOpening event only returns the layer, and all symbols together with the layer are highlighted/selected. 

![image](https://user-images.githubusercontent.com/8011074/75191757-f6d5d400-5720-11ea-9d62-f7f5f615c13e.png)

So, is it possible to select/highlight the symbol only and retrieve it? In other words, can the TableOfContentContextMenuOpening event return symbol as well? If possible, I can utilize the Symbol Display control provided in the toolkit to edit the specific symbol selected in TOC, which will make the toolkit more useful and integrated. 

Please consider adding this feature/implementation if doable. Thanks!

**Comment by dotMorten** [comment]
Way ahead of you. See the to enhancements branch (note it has some breaking changes)

**Comment by GeoITwinkle** [comment]
Oh, that's nice. I didn't notice that branch is doing this. I will take a look. Thanks!

**Comment by dotMorten** [comment]
Note that the symbol reference you get isn't the same reference that's in the renderer. You'd have to try and find it. See example here:
https://github.com/Esri/arcgis-runtime-demos-dotnet/blob/1d87a784f58942c4c499e36958a68a465e8de51e/src/SymbolEditor/SymbolEditorApp/MainWindow.xaml.cs#L75
