### ISSUE TITLE
Table of Contents: Legend does not refresh after symbol is modified

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-toolkit-dotnet#316]
I pulled the newest commit from master branch, built a local NuGet, and added an item into TOC's context menu to change the color of symbol randomly. The map refreshes correctly, but the legend does not. Below is the code for your testing.

[WpfApp1.zip](https://github.com/Esri/arcgis-toolkit-dotnet/files/4251678/WpfApp1.zip)

The real scenario is that I customized a Symbol Editor to edit all properties of the symbol. The map refreshes correctly, while the legend does not. I prefer using the master branch instead of the TocEhancement branch so that I do not need to change my code.

Please advise if I am missing some important code here, such as forcing the legend to refresh? I checked the LegendInfo class, but it does not have any modifiable properties.

Thanks!

**Comment by dotMorten** [comment]
There is unfortunately no event to react to, that would cause the legend to refresh, so there's no way for the legend to refresh itself. I've already added a method to the TocItem to trigger a refresh in the `tocenhancements` branch.
You can see the call to RefreshLegend here, after I applied the changes to the renderer:
https://github.com/Esri/arcgis-runtime-demos-dotnet/blob/SymbolEditor/src/SymbolEditor/SymbolEditorApp/MainWindow.xaml.cs#L46

**Comment by GeoITwinkle** [comment]
I see. If there is no workaround at present in master branch, I think the only way is to use the TOC branch. Thanks!

**Comment by dotMorten** [comment]
I hope to merge this week, and ship an update next week

**Comment by GeoITwinkle** [comment]
I was able to use the TocEnhancement branch to refresh the legend, and I was also able to use double click event to edit the symbol. the new TocItem class is a very good design. I am looking forward to the official merge and release. Thanks again for making the TOC better and better.
