### ISSUE TITLE
How to use these controls in the shared  project

### ISSUE THREAD

**Issue by nikh0001** [Esri/arcgis-toolkit-dotnet#320]
I am creating an app targetting UWP Android and iOS and want to use the toolkit. The toolkit is referenced in my project but when I try to use it in my XAML file located in the shared project folder it doesnt allow me to use the toolkit controls whereas I am able to use it on platform specific folders.  
How can I use these controls in the shared project template.
Please let me know.

**Comment by dotMorten** [comment]
@nikh0001 Make sure the toolkit is referenced by each of the projects that also references the shared project. A shared project is really nothing more than linked file into each project head, so those project heads needs to know the type.

In general I'd recommend using .NET Standard projects over shared projects if you can.
