### ISSUE TITLE
iOS: ScaleLine double-renders in some cases

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#324]
While running an app, the ScaleLine appears to render the design-time view in addition to the run-time view:

![image](https://user-images.githubusercontent.com/3381768/78595194-71087680-77fe-11ea-9220-04cd215d7b15.png)

When this issue occurs the ScaleLine is visually corrupted, because it displays a conflicting and incorrect scale in addition to the correct one.

**Steps to Reproduce**
Run the [Toolkit sample app](https://github.com/Esri/arcgis-toolkit-dotnet/tree/master/src/Samples/Toolkit.SampleApp.iOS) on iOS.  

When witnessed, this was occurring every time - it's not clear is there is specific to the environment that compels this to happen. 

When this occurs, it appears to be caused by `Initialize` being called twice:
- [here](https://github.com/Esri/arcgis-toolkit-dotnet/blob/8c3cb0e1948a107e4b40027cbc36b99153e74560/src/Toolkit/Toolkit.iOS/UI/Controls/ScaleLine/ScaleLine.iOS.cs#L46) 
- [here](https://github.com/Esri/arcgis-toolkit-dotnet/blob/8c3cb0e1948a107e4b40027cbc36b99153e74560/src/Toolkit/Toolkit.iOS/UI/Controls/ScaleLine/ScaleLine.iOS.cs#L55)

This issue was not encountered in previous usage, so presumably there are some cases where only one of the invocations is hit at run-time.  A simple check to guard against multiple invocations should be sufficient to avoid it. 

Version reproduced:  100.2.1-beta3

**Comment by nCastle1** [comment]
I have not been able to repro with the latest release, closing.
