### ISSUE TITLE
AR kit for WPF?

### ISSUE THREAD

**Issue by chclose** [Esri/arcgis-toolkit-dotnet#325]
Hi there,

Just curious if there are plans for an AR kit for WPF.  Unless I missed it, I can only see kits for iOS, Android, and UWP.

Thanks!
Chris

**Comment by dotMorten** [comment]
We rely on ARKit for iOS and ARCore for Android. There's no AR library for Windows we can build on, so we currently have no plans for Windows.
We might do a GPS/Look-around based approach for UWP down the line (you've probably seen some (disabled) parts of that on the code base). I don't see us doing WPF as the APIs to do this bit relies on various Win10 APIs and the performance and blending that UWP/WinUI delivers with its SwapChainPanel

**Comment by chclose** [comment]
Thanks for your prompt response @dotMorten.

Cheers.
