### ISSUE TITLE
AR ARScreenToLocation

### ISSUE THREAD

**Issue by nicogis** [Esri/arcgis-toolkit-dotnet#332]
Project Android Xamarin - AR 100.8 - Event GeoViewTapped: in the event argument GeoViewInputEventArgs the location returns coordinate wgs84 of scene while position return PointF but arView.ARScreenToLocation(e.Position) almost always return null. Did I miss something ?

**Comment by nCastle1** [comment]
Hi @nicogis,

ARScreenToLocation will only return a result if ARCore is able to detect a plane/surface at the tapped location. Please pardon the poor quality illustration:

![image](https://user-images.githubusercontent.com/29742178/82461365-35a0cf00-9a6f-11ea-83e5-445698dd590e.png)

In the image, the green tree is a real-world object, and the yellow ray represents what is at the tapped screen location.

With ARScreenToLocation, if there is a physical object, the real-world location of the tapped real-world object is returned. If there is no object, or ARCore/ARKit fails to detect the object, nothing is returned. When you use the existing non-AR ScreenToLocation method, the location of the virtual scene object at the tapped point is returned. In the illustration above, that ends up being the basemap, which is very far away from the tree. 

Does that make sense? Its kind of hard to describe so let me know if a short video or other graphic explanation would be helpful.

**Comment by nicogis** [comment]
Ok, I need more test on the field ...
I put a switch with / without  ARScreenToLocation
Thank you
