### ISSUE TITLE
Support Renderer overrides in Legend

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#333]
### Support Renderer overrides in Legend

By default ArcGIS Pro and the MapViewer as applications display the renderer override for this feature service. ArcGIS Runtime Toolkit currently obtains the swatch from the Symbol without taking account of the Renderer override.

- Implementation requires use of the [Renderer.GetSymbol overload that takes a Boolean ](https://developers.arcgis.com/net/latest/wpf/api-reference/html/M_Esri_ArcGISRuntime_Symbology_Renderer_GetSymbol_1.htm) for `applyAttributeOverrides`.
- For test data see https://www.arcgis.com/home/item.html?id=cd2c9cc157454ac6bd1c8e8aa93279ec

**Comment by dotMorten** [comment]
Legend doesn't use the Renderer's GetSymbol method but uses the LayerContent's GetLegendInfo method which returns the symbols:

https://github.com/Esri/arcgis-toolkit-dotnet/blob/0bb4fda2ad2994c20dc985e102995ff32cb65aa6/src/Toolkit/Toolkit/UI/Controls/Legend/LegendDataSource.cs#L346

**Comment by mbranscomb** [comment]
This feature requires implementation within the API of support for [`AuthoringInfo`](https://developers.arcgis.com/web-map-specification/objects/authoringInfo/) metadata in the Webmap.
