### ISSUE TITLE
Popup viewer for iOS - text clipping when larger text is enabled in system settings

### ISSUE THREAD

**Issue by nCastle1** [Esri/arcgis-toolkit-dotnet#336]
Interestingly, the text itself doesn't appear to grow in size.

To repro, go to the Settings app, then choose **Accessibility-> Display & Text Size-> Larger Text** then use the slider at the bottom to choose the text size before running an app with the popup viewer.

<img height="500" src="https://user-images.githubusercontent.com/29742178/90573895-6676ca00-e16c-11ea-966a-98d5b8a8c6f7.jpeg" alt="screenshot showing clipped text in an iOS app" />

**Comment by dotMorten** [comment]
Likely this line needs to take this into account: https://github.com/Esri/arcgis-toolkit-dotnet/blob/f70a027d91e958d60a2560f365503b71e6664f85/src/Toolkit/Toolkit.iOS/UI/Controls/PopupViewer/PopupViewerTableSource.cs#L54

**Comment by nCastle1** [comment]
No repro; this was likely already fixed years ago. Verified on both Forms and native.
