### ISSUE TITLE
Popup control does not display in Forms.UWP in release mode

### ISSUE THREAD

**Issue by ZackAllen** [Esri/arcgis-toolkit-dotnet#344]
## Issue
The popup control does not display anything after the `PopupManager` is constructed when running in release mode. The control works correctly when running in debug. This happens in Forms.UWP with version 100.9.

## Steps to Reproduce

Run [this sample](https://github.com/Esri/arcgis-runtime-samples-dotnet/tree/master/src/Forms/Shared/Samples/Layers/ShowPopup) in Forms.UWP release mode.

**Comment by nCastle1** [comment]
I don't think this is a Toolkit bug. Like the Runtime types, Toolkit types also need to be specified to work around .NET Native issues on UWP.

In app.xaml.cs for the Forms UWP project, adding the following lines solves the problem for the samples project:

```cs
assembliesToInclude.Add(typeof(PopupViewer).GetTypeInfo().Assembly);
```
