### ISSUE TITLE
Native UWP Legend sample on windows 1803 throws error due to `CornerRadius` property missing.

### ISSUE THREAD

**Issue by pMaske** [Esri/arcgis-toolkit-dotnet#356]
Legend Sample when run on windows version 1803 (17134) throws exception
```
Legend Sample - The property 'CornerRadius' was not found in type 'Esri.ArcGISRuntime.Toolkit.UI.Controls.Legend'. [Line: 0 Position: 0
```

**Comment by dotMorten** [comment]
Property `CornerRadius` on the Control class was introduced in 17763: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.cornerradius?view=winrt-19041
When legend is trying to template bind that property it can't find it.
