### ISSUE TITLE
Tap-to-place 3D Model sample on ARToolkit XF.iOS crashes the app

### ISSUE THREAD

**Issue by adityatogani94** [Esri/arcgis-toolkit-dotnet#358]
The `Tap-To-Place 3D Model` sample crashes the app.

Workflow that I followed:

- Open the app
- Open the sample 
- Tap to place the model. Perform some interactions (Zoom in/Zoom out) on the model
- Hit the back button (app crashes)

Device used : iPad mini iPadOS 14.4
Platform : Xamarin.Forms iOS

**Comment by nCastle1** [comment]
I haven't been able to reproduce this with 100.13, closing.
