### ISSUE TITLE
OverviewMap

### ISSUE THREAD

**Issue by ldanzinger** [Esri/arcgis-toolkit-dotnet#360]
### Min-ship (High Priority)

* The overview map itself will be 2D only. For a 3D overview map, we will have a separate component called "overview scene" which will be prioritized separately
* The "main" geoview of the app can be either 2D map or 3D scene
* The overview map indicator should show the current view
* As your main geoview's viewpoint changes, the overview map is updated automatically
* The scale/LOD of the overview map should update automatically as the user zooms in on the main map. For example, If you are looking at a city level, we don't want the overview map to be at the World level - it should be somewhere around state or country level (depending on size of state/country)
* Extent indicator is a red solid line by default
* Basemap is the Esri Topographic Vector Basemap by default
* Works with API Keys 
* On mobile, the overviewmap's touch/click events should be ignored (no user panning or zooming) - it is for reference only. On Desktop, it will update the main map's viewpoint
* works across the dateline (likely need to normalize geometry)
* works if map is rotated

### Nice-to-haves (Moderate Priority)

The overview map's basemap can be changed/specified
The overview map's extent indicator should be customizable

Examples:

![image](https://user-images.githubusercontent.com/4107363/121597904-d8274980-ca06-11eb-98bf-25b68c05ea09.png)

![image](https://user-images.githubusercontent.com/4107363/121597930-de1d2a80-ca06-11eb-8c2e-4d420d614ae6.png)

![image](https://user-images.githubusercontent.com/4107363/121597479-63eca600-ca06-11eb-8b72-20612c2e0a17.png)

**Comment by nCastle1** [comment]
PR open: https://github.com/Esri/arcgis-toolkit-dotnet/pull/364

**Comment by nCastle1** [comment]
PR has been merged
