### ISSUE TITLE
Plans for .NET 6.0 MAUI support?

### ISSUE THREAD

**Issue by rbanks-willow** [Esri/arcgis-toolkit-dotnet#368]
The title says it all 

Just curious if any work has been started on creating a ,NET MAUI compatible toolkit?  We're currently looking at moving our native apps to MAUI and trying to decide if we wrap the Android/iOS toolkits or track along with any progress here.

**Comment by dotMorten** [comment]
We first need to add MAUI support to the runtime itself (which we do intend to do!), before we do it to the toolkit, but we absolutely have plans to do that as well. Since .NET MAUI doesn't ship until November, it'll have to be some time after that - hopefully not too long after though.

**Comment by mbranscomb** [comment]
... @rbanks-willow Are there specific controls/components which are high priority for you to see in MAUI (or even ones we might not have released yet for Xamarin Forms)?

If so, please let us know and we'll try our best to factor them into our planning.

Thanks

**Comment by rbanks-willow** [comment]
Thanks for the update!

@mbranscomb We're using turn by turn navigation with an ArcGIS Online web map. We also displaying the layers from the map, and have a GraphicsOverlay for some extra visualisation. Beyond that, there's not much more to it.

Our current mobile apps support layer filtering, a choice of base maps, and a light/dark mode toggle. These are all managed via our own UI elements so we can own our UX , and we then programatically set the properties on the map view based on those UI interactions.

Our mobile apps are currently Kotlin and Swift based, so any Xam.Forms related concerns aren't that important for us.

For context, I'd be happy to work with any pre-release builds you have once they become available. We'd like to move over to the unified app as quickly after Nov 9 as we can. The availability of ArcGIS components will be our constaint though, so pre-release builds will help us spot problems and test changes ealier and shorten the release window. 

Let me know if you need any more info, and thanks again for replying so promptly.

**Comment by mbranscomb** [comment]
@rbanks-willow That's great context, thanks.

It's possible we may be able to share a preview of API support for MAUI later this year, which would be a prerequisite for any Toolkit components built on top of MAUI. Please email me at mbranscomb@esri.com and I'll add you to the list of potential preview testers.
