### ISSUE TITLE
iOS: Compass does not redraw after resizing

### ISSUE THREAD

**Issue by mstefarov** [Esri/arcgis-toolkit-dotnet#373]
As seen in the native iOS sample for Compass:
Resizing the compass does not trigger a redraw. That means going from small to large size causes the compass to appear very blurry -- until the view is rotated.

![abeae600-feeb-11eb-93fd-9f454ca09bbd](https://user-images.githubusercontent.com/587809/129855128-c35c054d-de43-41cf-ad26-5235eb22c197.gif)

So we should probably be listening to viewDidLayoutSubviews event (called when compass is resized by its parent) and call SetNeedsDisplay() to redraw.

**Comment by nCastle1** [comment]
Issue resolved by #396
