### ISSUE TITLE
[ARToolkit] Black screen instead of camera on second and next usages of ARSceneView on select devices

### ISSUE THREAD

**Issue by kamszyc** [Esri/arcgis-toolkit-dotnet#382]
Hello,
in our testing of Xamarin.Forms ARSceneView we encountered very specific issue with ARSceneView control.

The scenario is to go to AR scene for at least two times.
When AR page is displayed for a second time, black screen is displayed instead of camera.
Objects on ArcGIS scene are rendered nonetheless.

Issue is reproducible using .NET samples application
https://github.com/Esri/arcgis-runtime-samples-dotnet
both Xamarin.Android and Xamarin.Forms one, e.g. using **View hidden infrastructure in AR** sample.

On the other hand, problem doesn't seem to occur on native Android SDK sample app, available on Google Play Store
https://play.google.com/store/apps/details?id=com.esri.sampleviewer

Very important thing is that issue seems to **NOT** occur on devices with Snapdragon processors.
We only managed to reproduce it on Huawei and Samsung phones with HiSilicon and Exynos SoCs.

Screenshot below is taken on Samsung Galaxy S9 phone with Samsung Exynos 9810 and 4GB of RAM.

![image](https://user-images.githubusercontent.com/11475524/138472807-8d2030df-3646-4624-800b-d6be99e1d7ba.png)

**Comment by kamszyc** [comment]
@mbranscomb
I want to share with you something I found out about this issue.

After I have commented out `RenderFrame()` call in `ARSceneView.Android.cs` file camera feed started to appear on affected device on every display of `ARSceneView`.
![image](https://user-images.githubusercontent.com/11475524/139837763-930b5ca5-afa2-40e2-98da-0d218aba20e8.png)

What this probably means is that ArcGIS `SceneView` covers camera feed up with black background instead of rendering transparent background.
So, it's possible that it's a problem with `SpaceEffect`/`AtmosphereEffect` implementation in `SceneView`.

**Comment by dotMorten** [comment]
@kamszyc nice find. Which device are you using for your testing where you see the issue?

**Comment by kamszyc** [comment]
@dotMorten As I explained in first comment:
I'm using Samsung Galaxy S9 with Samsung Exynos 9810 SoC.
It's very important for a phone to **NOT** have Qualcomm Snapdragon SoC, as issue doesn't seems to occur on such devices.

**Comment by dotMorten** [comment]
Aaah sorry I read it backwards as if that's the one it does work on. Thanks.

**Comment by kamszyc** [comment]
@dotMorten @mbranscomb 
Have you been able to reproduce this problem internally at Esri?
Do you maybe have an idea for a workaround that fixes this issue?

**Comment by dotMorten** [comment]
Thank you for finding this. Does the stop tracking call like the samples do not help: https://github.com/Esri/arcgis-toolkit-dotnet/blob/bd93da6d33551da85f5d5dd8ab219de8b69ebcd8/src/ARSamples/ARToolkit.SampleApp.Android/Samples/ARActivityBase.cs#L112

**Comment by kamszyc** [comment]
Yes, `StopTrackingAsync` call be itself seems to not help

**Comment by nCastle1** [comment]
I've noticed that this issue is easily reproduced with later versions of ARCore and SceneForm, even on a Samsung device with a Snapdragon processor. The proposed solution (https://github.com/Esri/arcgis-toolkit-dotnet/issues/382#issuecomment-977816476) appears to resolve the issue when using the latest ARCore and SceneForm packages.

**Comment by nCastle1** [comment]
@kamszyc The 100.13 nuget packages have been released for AR Toolkit. This release incorporates your proposed fix, among other changes. I haven't been able to reproduce the issue after these changes have been made, but I don't have access to anything other than Snapdragon to test with.

If you're able, please let us know if the updated version solves the problem with your device(s). Thank you!

**Comment by kamszyc** [comment]
@nCastle1 I tested our app with 100.13 packages and updated version solves the problem on Samsung Galaxy S9 with Exynos 9810 processor
Thank you for the fix, I'm closing this issue
