### ISSUE TITLE
Cannot build Samples on VSMac due to multi-targetting

### ISSUE THREAD

**Issue by jawbrey** [Esri/arcgis-toolkit-dotnet#383]
VS Mac will not build the Samples due to multi-targeting.  This error is generated during Nuget restore

> /usr/local/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(89,5) : error NETSDK1100: Windows is required to build Windows desktop applications.

**Comment by nCastle1** [comment]
Unfortunately, building Toolkit on Mac is currently not supported; you'll need to use Windows. I took some time to try adapting the solution to work on Mac, and couldn't make much progress. Sharing code among UWP, WPF (Framework and .NET 6), Xamarin.Forms, iOS, .NET Standard, and Android is an uncommon scenario, and even Visual Studio on Windows can't handle it very reliably.

I'll make a note to re-test with Visual Studio for Mac 2022 when it is released.
