### ISSUE TITLE
Can't create a "Hello World" app with a BasemapGallery tool

### ISSUE THREAD

**Issue by michkowalczuk** [Esri/arcgis-toolkit-dotnet#387]
I simply added code from your toolkit page (https://esri.github.io/arcgis-toolkit-dotnet/basemap-gallery.html) and had following errors. 
Using a last nuget version. 

![arcgis runtime toolkit basemapgallery](https://user-images.githubusercontent.com/23641410/144192925-5fc82a8a-0373-4222-a284-33ad05a3b66f.png)

**Comment by dotMorten** [comment]
The basemap gallery isn't in the nuget packages yet, and still a work in progress. If you need it now, you'll need to build the toolkit yourself, or wait for the next release of the toolkit.
