### ISSUE TITLE
ARToolkit v100.13 missing on Nuget

### ISSUE THREAD

**Issue by kamszyc** [Esri/arcgis-toolkit-dotnet#407]
Unlike Toolkit and Toolkit Forms, ARToolkit and ARToolkit.Forms v100.13 are not uploaded to nuget.org

**Comment by nCastle1** [comment]
Apologies for the lack of updates. The AR toolkit was delayed so we could fix some issues affecting Android. Testing took a bit longer than expected, and we weren't ready to publish before the holidays. I am planning on testing the final built packages today, and if everything goes as planned, they should be published soon after. I will comment on this issue once the packages are live.

**Comment by nCastle1** [comment]
@kamszyc The 100.13 AR toolkit packages have been published to Nuget, so I'm closing this issue. Please log another if you see any problems.
