### ISSUE TITLE
[Question] Security policy

### ISSUE THREAD

**Issue by milfordjosh** [Esri/arcgis-toolkit-dotnet#456]
Hi,
I see that there is no security policy listed currently for this project. Is there any such security policy that exists and is being used for this project development?
For example:
https://www.microsoft.com/en-us/securityengineering/sdl/practices
Thanks!

**Comment by mbranscomb** [comment]
@milfordjosh 

Hi,

Thanks for your question. You can find Esri's overall security policy at https://trust.arcgis.com, and if you have any specific concerns they can be reported at https://trust.arcgis.com/en/security-concern/.

We'll investigate and determine the appropriate content to specifically list for this, and other similar projects.

Thanks

**Comment by milfordjosh** [comment]
Thank you for the quick answer. I was able to find exactly the information I needed on that page, including this pdf:
https://downloads.esri.com/RESOURCES/ENTERPRISEGIS/Esri_SDLC.pdf
Very much appreciated!
