### ISSUE TITLE
Support OAuth user login for ArcGIS Online org entered at runtime

### ISSUE THREAD

**Issue by dbroux** [Esri/arcgis-toolkit-dotnet#81]
Tweak the provided WinPhone and Desktop  OAuthAuthorize components to support this workflow.

We may also consider providing a WinStore OAutAuthorize component based on the WebView that supports this workflow (seems there is no way to support this workflow with the WebAuthenticationBroker)

**Comment by rexhansen** [comment]
Verified.  Unfortunately, on phone it requires use a web view instead of web authentication broker.
